# Generated by Django 2.0.6 on 2018-06-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180616_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='images',
            new_name='images/',
        ),
    ]
